#pragma once

#include <sdkconfig.h>

#ifndef CONFIG_CAPTURE_SCHEDULER_LOG_TAG
#define CONFIG_CAPTURE_SCHEDULER_LOG_TAG                 "CAPTUREHANDLER"
#endif /* CONFIG_CAPTURE_SCHEDULER_LOG_TAG */
#define CAPTUREHANDLERTAG CONFIG_CAPTURE_SCHEDULER_LOG_TAG