/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "live_stream.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(open_gopro_NotifyLiveStreamStatus, open_gopro_NotifyLiveStreamStatus, AUTO)


PB_BIND(open_gopro_RequestGetLiveStreamStatus, open_gopro_RequestGetLiveStreamStatus, AUTO)


PB_BIND(open_gopro_RequestSetLiveStreamMode, open_gopro_RequestSetLiveStreamMode, AUTO)








