/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "network_management.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(open_gopro_NotifProvisioningState, open_gopro_NotifProvisioningState, AUTO)


PB_BIND(open_gopro_NotifStartScanning, open_gopro_NotifStartScanning, AUTO)


PB_BIND(open_gopro_RequestConnect, open_gopro_RequestConnect, AUTO)


PB_BIND(open_gopro_RequestConnectNew, open_gopro_RequestConnectNew, AUTO)


PB_BIND(open_gopro_RequestGetApEntries, open_gopro_RequestGetApEntries, AUTO)


PB_BIND(open_gopro_RequestReleaseNetwork, open_gopro_RequestReleaseNetwork, AUTO)


PB_BIND(open_gopro_RequestStartScan, open_gopro_RequestStartScan, AUTO)


PB_BIND(open_gopro_ResponseConnect, open_gopro_ResponseConnect, AUTO)


PB_BIND(open_gopro_ResponseConnectNew, open_gopro_ResponseConnectNew, AUTO)


PB_BIND(open_gopro_ResponseGetApEntries, open_gopro_ResponseGetApEntries, AUTO)


PB_BIND(open_gopro_ResponseGetApEntries_ScanEntry, open_gopro_ResponseGetApEntries_ScanEntry, AUTO)


PB_BIND(open_gopro_ResponseStartScanning, open_gopro_ResponseStartScanning, AUTO)






