/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "response_generic.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(open_gopro_ResponseGeneric, open_gopro_ResponseGeneric, AUTO)


PB_BIND(open_gopro_Media, open_gopro_Media, AUTO)




